---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      build_args:
        - UNIVERSITY=gu
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: codinglion/videochat-gannon
      #   auto_tag: true
      tags:
        - ${DRONE_BRANCH}
        - latest
---
kind: signature
hmac: fee16acbb0c1336699567caa7aef5e53db266ce9a5962cc6151a4c0cf69c6268

...
