---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      build_args:
        - UNIVERSITY=$${university}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: codinglion/videochat-gannon
      #   auto_tag: true
      tags:
        - ${DRONE_BRANCH}
        - latest
---
kind: signature
hmac: cf7f29d9f919276ee6e51cf5c4132b4dd3849224a4cbe239a4420cfda820ac79

...
