kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      UNIVERSITY:
        from_secret: university
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: codinglion/videochat-gannon
      auto_tag: true
      tags:
        - ${DRONE_BRANCH}
