---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      build_args:
        UNIVERSITY:
          from_secret: university
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: codinglion/videochat-gannon
      #   auto_tag: true
      tags:
        - ${DRONE_BRANCH}
        - latest
---
kind: signature
hmac: 304a613403a3bdc7c2a48d59f9a213bcc96b7b46395fa12596b4fd0d173b9d47

...
